name: MahiOpsAI DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Manual Git Clone
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jagdishmaliwad2002/MahiOpsAI2.0.git .

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mahiopsai:latest ./docker

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mahiopsai:latest
